language: java
sudo: false
install: true

jdk:
  - oraclejdk8

  notifications:
    email:
      recipients:
        - ybronshteyn@blackducksoftware.com
  
script:
  ./gradlew build

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)