language: java
sudo: false
install: true
dist: trusty

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - dmeurer@synopsys.com

script:
  ./gradlew build

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
