server:
  port: 8666
spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/bds_hub_concourse
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: bds_hub_scm_integration
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    favicon:
      enabled: false
  main:
    banner-mode: 'off'
  freemarker:
    cache: false
debug:
  buildLogDirectory:
blackduck:
  hub-scm:
    static-location: /static
    