version: '3.1' 

services:
  hub-scm-ui:
    labels: 
      hub-scm:
    image: blackducksoftware/hub-scm-ui
    depends_on: [hub-scm-db, concourse-web]
    ports: ["8666:8666"]
    links: [hub-scm-db, concourse-web]
    environment: 
      spring.datasource.url: 'jdbc:postgresql://hub-scm-db:5432/hubconcourse'
      spring.datasource.username: blackduck
      spring.datasource.password: "${DB_PASSWRD}"
      concourse.username: concourse
      concourse.url: "http://concourse-web:8080"
      concourse.password: "${CONCOURSE_PASSWRD}"
      blackduck.hub.url: ${HUB_URL}
      blackduck.hub.username: ${HUB_USERNAME}
      blackduck.hub.password: ${HUB_PASSWORD}
  hub-scm-db:
    labels: 
      hub-scm:
    image: postgres:9.5
    environment:
      POSTGRES_DB: hubconcourse
      POSTGRES_USER: blackduck
      POSTGRES_PASSWORD: "${DB_PASSWRD}"
      PGDATA: /database
  concourse-web:
    labels: 
      hub-scm:
    image: concourse/concourse:3.5.0
    links: [hub-scm-db]
    command: web --encryption-key ${ENCRYPTION_KEY}
    depends_on: [hub-scm-db]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until concurse-db comes up
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: "${CONCOURSE_PASSWRD}"
      CONCOURSE_EXTERNAL_URL: "http://concourse-web:8080"
      CONCOURSE_POSTGRES_HOST: hub-scm-db
      CONCOURSE_POSTGRES_USER: blackduck
      CONCOURSE_POSTGRES_PASSWORD: "${DB_PASSWRD}"
      CONCOURSE_POSTGRES_DATABASE: hubconcourse
  concourse-worker:
    labels: 
      hub-scm:
    image: concourse/concourse:3.5.0
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web

